services:
  postgresql:
    image: docker.io/bitnami/postgresql:17
    ports:
      - "5432:5432"
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    environment:
      POSTGRESQL_PASSWORD: postgresql_secret_password
      POSTGRESQL_POSTGRES_PASSWORD: postgresql_postgres_secret_password
    restart: on-failure

volumes:
  postgresql_data:
    driver: local
