services:
  postgresql:
    image: docker.io/bitnami/postgresql:17
    ports:
      - "5432:5432"
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    environment:
      POSTGRESQL_MAX_CONNECTIONS: 500
      POSTGRESQL_DATABASE: postgres
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_POSTGRES_PASSWORD: ${POSTGRESQL_POSTGRES_PASSWORD}
    restart: always

volumes:
  postgresql_data:
    driver: local
