services:
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - redis_data:/data
    restart: on-failure

volumes:
  redis_data:
