services:
  scheduler:
    image: bo/task-scheduler
    build:
      context: ../../
      dockerfile: tasks.scheduler.Dockerfile
    container_name: bo-task-scheduler
    networks:
      - redis-stack-task-network
    restart: always
    environment:
      BO_REDIS_URL: ${BO_REDIS_URL}
      BO_REDIS_HOSTNAME: bo-redis-stack
      BO_TASK_SCHEDULER: 1
      BO_LOG_FILE: bobuild_scheduler.log

networks:
  redis-stack-task-network:
    external: true
    name: redis-task-network
