import platform
from dataclasses import dataclass
from dataclasses import field
from pathlib import Path

from boltons.cacheutils import cachedproperty

from bobuild.utils import get_var

_repo_dir = Path(__file__).parent.parent.resolve()

if platform.system() == "Windows":
    # NOTE: this is mirrored in install_steamcmd.ps1.
    _default_steamcmd_install_dir = str(_repo_dir / "bin/steamcmd/")
    _default_repo_path = Path().home() / "Documents/My Games/Rising Storm 2/ROGame/Src/WW2"
    _default_rs2_game_dir = r"C:\rs2vietnam\\"
    _default_rs2_server_dir = r"C:\rs2server\\"
    _steamcmd_exe_name = "steamcmd.exe"
else:
    # TODO: set good defaults for Linux too?
    _default_steamcmd_install_dir = "TODO"
    _default_repo_path = "TODO"  # type: ignore[assignment]
    _default_rs2_game_dir = "TODO"
    _default_rs2_server_dir = "TODO"
    _steamcmd_exe_name = "steamcmd.sh"
    raise NotImplementedError


@dataclass(frozen=True)
class MercurialConfig:
    @cachedproperty
    def username(self) -> str:
        return get_var("BO_HG_USERNAME")

    @cachedproperty
    def password(self) -> str:
        return get_var("BO_HG_PASSWORD")

    @cachedproperty
    def pkg_repo_path(self) -> Path:
        return Path(get_var("BO_HG_PKG_REPO_PATH")).resolve()

    @cachedproperty
    def maps_repo_path(self) -> Path:
        return Path(get_var("BO_HG_MAPS_REPO_PATH")).resolve()

    @cachedproperty
    def pkg_repo_url(self) -> str:
        return get_var("BO_HG_PKG_REPO_URL")

    @cachedproperty
    def maps_repo_url(self) -> str:
        return get_var("BO_HG_MAPS_REPO_URL")

    @cachedproperty
    def hgrc_path(self) -> Path:
        return (Path.home() / ".hgrc").resolve()


@dataclass(frozen=True)
class GitConfig:

    @cachedproperty
    def token(self) -> str:
        return get_var("BO_GITHUB_TOKEN")

    @cachedproperty
    def repo_url(self) -> str:
        return f"https://oauth2:{self.token}@github.com/adriaNsteam/WW2.git"

    @cachedproperty
    def repo_path(self) -> Path:
        return Path(get_var("BO_GITHUB_REPO_PATH",
                            _default_repo_path)).resolve()

    @cachedproperty
    def branch(self) -> str:
        return get_var("BO_GITHUB_BRANCH", "main")


@dataclass(frozen=True)
class SteamCmdConfig:
    """
    TODO: SteamCMD installation logic is duplicated in
      install_steamcmd.ps1. Do we need both, Python and PowerShell
      versions? Maybe get rid of the PS version and handle everything
      with the Python scripts?
    """

    download_url: str = "https://steamcdn-a.akamaihd.net/client/installer/steamcmd.zip"

    @cachedproperty
    def install_dir(self) -> Path:
        return Path(get_var("BO_STEAMCMD_INSTALL_DIR",
                            _default_steamcmd_install_dir)).resolve()

    @cachedproperty
    def exe_path(self) -> Path:
        return self.install_dir / _steamcmd_exe_name

    @cachedproperty
    def username(self) -> str:
        return get_var("BO_STEAMCMD_USERNAME")

    @cachedproperty
    def password(self) -> str:
        return get_var("BO_STEAMCMD_PASSWORD")

    @cachedproperty
    def steamguard_passkey(self) -> str:
        return get_var("BO_STEAMGUARD_PASSKEY", "")

    @cachedproperty
    def steamguard_cli_path(self) -> Path:
        # NOTE: this path is mirrored in install_steamguardcli.ps1.
        return Path(_repo_dir / "bin/steamguard.exe")


# NOTE: This dict is generated by bobuild.workshop.first_time_upload_all_maps.
# If the number of maps changes, generate this again! There is some manual
# labor involved in doing so, so be warned!
def map_ids_factory() -> dict[str, int]:
    return {
        "DRTE-Bardia": 3406027068,
        "DRTE-ElAlamein": 3406027112,
        "DRTE-HalfayaPass": 3406027154,
        "DRTE-Leros": 3406027188,
        "DRTE-LongstopHill": 3406027233,
        "DRTE-Mareth": 3406027284,
        "DRTE-Medjez": 3406027340,
        "DRTE-Tobruk": 3406027379,
        "RRTE-Apartments": 3406027430,
        "RRTE-Barashka": 3406027493,
        "RRTE-Barracks": 3406027524,
        "RRTE-Beach_Invasion_Sim": 3406027563,
        "RRTE-Betio": 3406027608,
        "RRTE-BiblioHill": 3406027658,
        "RRTE-Brecourt": 3406027716,
        "RRTE-CommissarsHouse": 3406027788,
        "RRTE-Demyansk": 3406027841,
        "RRTE-FallenFighters": 3406027903,
        "RRTE-Foy": 3406027958,
        "RRTE-GrainElevator": 3406028011,
        "RRTE-GuadalCanal": 3406028070,
        "RRTE-HacksawRidge": 3406028118,
        "RRTE-Halbe_BreakoutBlockOut": 3406028186,
        "RRTE-Hanto": 3406028229,
        "RRTE-HellsCorners": 3406028273,
        "RRTE-HirosakiCastle": 3406028320,
        "RRTE-Horson": 3406028350,
        "RRTE-IwoJima": 3406028389,
        "RRTE-Kobura": 3406028418,
        "RRTE-Kwajalein": 3406028460,
        "RRTE-MaggotHill": 3406028490,
        "RRTE-MamayevKurgan": 3406028541,
        "RRTE-MarcoPolo": 3406028585,
        "RRTE-Mutanchiang": 3406028629,
        "RRTE-MyshkovaRiver": 3406028683,
        "RRTE-Oosterbeek": 3406028741,
        "RRTE-PavlovsHouse": 3406028807,
        "RRTE-Peleliu": 3406028861,
        "RRTE-PortBrest": 3406028917,
        "RRTE-RamreeIsland": 3406028965,
        "RRTE-RedOctoberFactory": 3406029012,
        "RRTE-Reichstag": 3406029064,
        "RRTE-Saipan": 3406029097,
        "RRTE-Shumshu": 3406029204,
        "RRTE-ShuriCastle": 3406029250,
        "RRTE-Spartanovka": 3406029296,
        "RRTE-Station": 3406029339,
        "RRTE-Suribachi": 3406029403,
        "RRTE-Univermag": 3406029450,
    }


@dataclass(frozen=True)
class RS2Config:
    bo_dev_beta_workshop_id: int = 3404127489
    bo_dev_beta_map_ids: dict[str, int] = field(default_factory=map_ids_factory)

    @cachedproperty
    def game_install_dir(self) -> Path:
        return Path(get_var("BO_RS2_GAME_INSTALL_DIR",
                            _default_rs2_game_dir)).resolve()

    @cachedproperty
    def server_install_dir(self) -> Path:
        return Path(get_var("BO_RS2_SERVER_INSTALL_DIR",
                            _default_rs2_server_dir)).resolve()

    @cachedproperty
    def rs2_documents_dir(self) -> Path:
        return Path.home() / "Documents/My Games/Rising Storm 2"

    @cachedproperty
    def published_dir(self) -> Path:
        return self.rs2_documents_dir / "ROGame/Published/"

    @cachedproperty
    def unpublished_dir(self) -> Path:
        return self.rs2_documents_dir / "ROGame/Unpublished/"

    @cachedproperty
    def vneditor_exe(self):
        return self.game_install_dir / "Binaries/Win64/VNEditor.exe"


@dataclass(frozen=True)
class DiscordConfig:
    @cachedproperty
    def builds_webhook_url(self) -> str:
        return get_var("BO_DISCORD_BUILDS_WEBHOOK")
