name: Build Docker images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  docker:
    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build tasks.scheduler.Dockerfile
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: bo/task-scheduler
          file: tasks.scheduler.Dockerfile
          build-args: |
            VCPKG_BINARY_SOURCES=${{ env.VCPKG_BINARY_SOURCES }}
            ACTIONS_CACHE_URL=${{ env.ACTIONS_CACHE_URL }}
            ACTIONS_RUNTIME_TOKEN=${{ env.ACTIONS_RUNTIME_TOKEN }}

      - name: Build discord.build-command-bot.Dockerfile
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: bo/discord-build-command-bot
          file: discord.build-command-bot.Dockerfile
          build-args: |
            VCPKG_BINARY_SOURCES=${{ env.VCPKG_BINARY_SOURCES }}
            ACTIONS_CACHE_URL=${{ env.ACTIONS_CACHE_URL }}
            ACTIONS_RUNTIME_TOKEN=${{ env.ACTIONS_RUNTIME_TOKEN }}
