name: Build Docker images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build tasks.scheduler.Dockerfile
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: bo/task-scheduler
          file: tasks.scheduler.Dockerfile

      - name: Build discord.build-command-bot.Dockerfile
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: bo/discord-build-command-bot
          file: discord.build-command-bot.Dockerfile
