name: Test and package Python project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11", "3.12", "3.13" ]
        os: [ "ubuntu-latest", "windows-latest" ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.os }} ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]

      - name: Build project with Hatch
        run: |
          hatch build

      - name: Check types with MyPy
        run: |
          hatch run test:mypy

      - name: Lint code with Ruff
        run: |
          hatch run test:ruff

      - name: Check import sorting
        run: |
          hatch run test:isort
